### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atherdon** [zjor/eth_sol_course_code#1]
.

**Comment by zjor** [comment]
Hi, Arthur, 
nice idea! I saw a couple of projects like this, even failing ones but still it may work with an appropriate business model. How do you plan to make money out of it? For example, you can integrate with food delivery companies and let people order the complete list of products for the recipe, let's say I want to cook Pho today, so I order noodles, meet, e.t.c. in one click. Or you can even propose menu for the whole week.
As for coding I'm quite busy these days but if you have something small and isolated I may help.
Good luck with the project!
btw, I was born in Kharkiv :)
